# Generated by Django 5.0 on 2023-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=50)),
                ('kode', models.CharField(max_length=40)),
                ('harga', models.IntegerField(null=True)),
            ],
        ),
    ]
