# Generated by Django 5.0 on 2023-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasirku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.FloatField(null=True),
        ),
    ]
