# Generated by Django 5.0 on 2023-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasirku', '0002_alter_barang_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
