# Generated by Django 5.0 on 2023-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasirku', '0003_barang_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='diskon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
